### ISSUE TITLE
Include useful github actions

### ISSUE THREAD

**Issue by AndersonTorres** [museoa/bqn-mode#16]
bqn-mode is a somewhat simple package, in the sense it is just a set of files to be read by Emacs. In this sense it works very well. 

However, in order to include it in MELPA database, there are many rules to follow. We need some way to automatize this.

**Comment by svmhdvn** [comment]
https://github.com/riscy/melpazoid I think this should work perfectly right? I don't have more time this week but I think this looks easy enough to integrate based on the instructions.

**Comment by AndersonTorres** [comment]
Looks fine!
