### ISSUE TITLE
Error: Can’t activate input method ‘BQN-Z’

### ISSUE THREAD

**Issue by oantolin** [museoa/bqn-mode#23]
If your first interaction with bqn-mode in a given Emacs session is to open a REPL via `bqn-comint-run-process`, you get the error message in the title. A simple fix is to require `bqn-key-prefix` in `bqn-comint.el`.

(The fact that `bqn-comint-run-process` has autoload suggests one should be able to run it first thing.)

**Comment by oantolin** [comment]
For now I'm using this workaround in my personal configuration: `(use-package bqn-key-prefix :after bqn-comint)`.

**Comment by AndersonTorres** [comment]
@oantolin can you verify if it is fixed now?

**Comment by oantolin** [comment]
Yep, that fixes it. Thanks!
