### ISSUE TITLE
[Bug] No syntax face for comments

### ISSUE THREAD

**Issue by skykanin** [museoa/bqn-mode#35]
`bqn-mode` doesn't seem to set a syntax face for comments which means that comments don't use the BQN386 Unicode font by default.
![image](https://user-images.githubusercontent.com/3789764/228313920-43fa7948-94b7-4f60-b372-fc0e6c2840bf.png)

**Comment by AndersonTorres** [comment]
Can you provide the text that generated this print?

**Comment by skykanin** [comment]
> Can you provide the text that generated this print?

`Windows ← {𝕨 ↕ 1 + ↕ 𝕩} # 𝕨 element windows in 1-indexed range 𝕩`

**Comment by AndersonTorres** [comment]
Now I am feeling the need to study how to debug Elisp packages.

When I use `emacs -q` and executes (manually, via `M-:`) the code

```elisp
(add-to-list 'load-path "/bqn-mode-source/trunk/")
(require 'bqn-mode)
```

it font-locks a file with the code above with no issues... I will investigate a bit more.

![emacs-unsolved](https://user-images.githubusercontent.com/5954806/229379253-934fac50-046b-4ffb-bf07-1138ab114926.png)

**Comment by ilohmar** [comment]
This should be solved by PR #40.

**Comment by AndersonTorres** [comment]
Hello, @skykanin! Can you verify if this is working now?

**Comment by skykanin** [comment]
@AndersonTorres tested on b1f7f062b87dc5de84e0f00b7b5d895bf862af90, but it doesn't seem to have fixed it. Comments still use my set emacs font instead of BQN386. My current workaround in doom emacs is this:
```
;; Set BQN386 font in other bqn major modes. `bqn-mode' already uses the font by default,
;; however we include it here as well because comments aren't covered by the font faces.
(add-hook! '(bqn-mode-hook bqn-comint-mode-hook bqn-keymap-mode-hook bqn-glyph-mode-hook)
           (face-remap-add-relative 'default '(:family "BQN386 Unicode")))
```

**Comment by ilohmar** [comment]
I just tested from `emacs -q` again, simply loading bqn-mode and opening a bqn file --- the whole buffer uses the same BQN font (or the best fallback font, in my case).  Can you reproduce the issue without doom?  Otherwise please file a bug with doom emacs.

**Comment by AndersonTorres** [comment]
I have a feeling it can be a subtle bug, maybe some configuration that goes too far either in bqn or doom.

**Comment by ilohmar** [comment]
The workaround looks suspicious to me, this is basically a fragile separate way to achieve what should be the default now, anyway.  Does Doom (or do you in your config) customize bqn faces, and if so, what does the customization look like?

**Comment by skykanin** [comment]
Seems like doom doesn't upgrade projectile packages with new pinned commits unless you pass the `--upgrade` flag in the CLI. After upgrading properly and removing my workaround the comment font face works correctly. :raised_hands:
