### ISSUE TITLE
[Bug] bqn-mode interprets '#' as a comment

### ISSUE THREAD

**Issue by skykanin** [museoa/bqn-mode#55]
It seems that the font face/s used in `bqn-mode` interprets `'#'` as a comment instead of a character. Tested on  0a51e0930bfbf41ae32b28b8bdec76b92bd311da.

Code examples:

- `'#'= (⊢|·1‿3⊸×¨↕)∘(¯1⊸⊑∘≢)⊸⊑`
- `'#' = '.'`
- `'#' = '#'`

![image](https://user-images.githubusercontent.com/3789764/232851428-45ea62ad-1c17-474c-8f5a-0a051fc72005.png)

**Comment by AndersonTorres** [comment]
@skykanin can you verify? Just in case.

**Comment by AndersonTorres** [comment]
It looks fine to me. I will close this.

![bug2](https://user-images.githubusercontent.com/5954806/233647440-a9fb5c10-6d18-4c93-8ed1-bc2455a772c2.png)

**Comment by skykanin** [comment]
@AndersonTorres sorry for the delay. Yes it is fixed now :+1:
