### ISSUE TITLE
Implementing code evaluation

### ISSUE THREAD

**Issue by luxbock** [museoa/bqn-mode#69]
It's nice to be able to evaluate code within a source file while seeing the results appear without visiting the comint buffer. I've implemented this, and could push it as a feature with some further tidying up.

If there's interest for it, I could also try to add evaluation results via an overlay in the buffer itself, so that the evaluation results would appear next to the code. It's a slight UI improvement to moving your eyes to the echo area at the bottom of the buffer.

**Comment by AndersonTorres** [comment]
Go for it!
