### ISSUE TITLE
org-babel support

### ISSUE THREAD

**Issue by luxbock** [museoa/bqn-mode#70]
Should we add org-babel support within this repository? I suppose eventually you'd want to add it to org-mode itself, but it might be a good idea to include it here as a first go?

**Comment by AndersonTorres** [comment]
Hum, how precisely an org-babel support for an extra language is distributed?

**Comment by luxbock** [comment]
I am not sure how it generally works.

For some languages they are included with org-mode and thus as a part of Emacs itself:

https://orgmode.org/worg/org-contrib/babel/languages/index.html

That page mentions that other languages are included in ELPA, but I was only able to find `ob-haxe` on a quick look.

In my mind early on it might make sense just to include it here, at least while we don't have a full implementation but just one that lets you show source code and evaluate results.

**Comment by AndersonTorres** [comment]
Well, I am certainly for including it here. My question is: how can someone find and use it?

**Comment by AndersonTorres** [comment]
Closing as completed
