### ISSUE TITLE
Syntax table entries for · and @ are causing incorrect highlighting

### ISSUE THREAD

**Issue by y0sik** [museoa/bqn-mode#74]
Right now, `·` and `@` are marked as symbols (using "_") in syntax table. That feels strange and also causes misleading highlighting in cases like `·Foo` or `Foo@` (they are valid syntactically but highlighted with `error` face). It also causes some functions (e.g. `isearch-forward-symbol-at-point`) to treat these characters as parts of the identifier.

I think that they should be marked as punctuations (using ".").

**Comment by AndersonTorres** [comment]
Let's test, then.

**Comment by AndersonTorres** [comment]
@y0sik can you test the tip of develop branch, please?

**Comment by y0sik** [comment]
Yep, that seems to work. Thanks!

**Comment by AndersonTorres** [comment]
I will promote it to trunk.
