### ISSUE TITLE
How to get live process running and evaluate code?

### ISSUE THREAD

**Issue by b79** [museoa/bqn-mode#77]
I'm trying to get Emacs set up with BQN. I've installed bqn-mode, and the color syntax and backslash prefixes used to input BQN unicode notation are working fine. But how to evaluate code? After creating a file `example1.bqn` with some simple expressions in it and making sure we're in bqn-mode, I try `bqn-comint-send-buffer`, `bqn-comint-send-region`, `bqn-comint-send-buffer` etc. only to get:

    Buffer ’*BQN*’ exists but has no live process

How to I get a "live process" running? Browsing through the functions in bqn-mode.el, it's not clear to me.

**Comment by b79** [comment]
For context, I'm running Doom Emacs under Emacs version 28.2.  Could it be something's missing from my use-package statement? Here's what I have in config.el :

```elisp
(use-package bqn-mode
 :ensure t
 :init
 (require 'bqn-mode)
 (require 'bqn-keymap-mode)
 (require 'bqn-glyph-mode)
 (setq bqn-interpreter "$HOME/comp/lang/array-languages/bqn/CBQN/BQN")
 (setq bqn-comint-interpreter-path "$HOME/comp/lang/array-languages/bqn/CBQN/BQN")
 :bind (("C-c B" . run-bqn)
		("C-c C-c C-e" . bqn-comint-send-buffer)
		("C-c C-x C-e" . bqn-comint-send-region))
 :config
 (defun run-bqn ()
   "Pop up a BQN REPL."
   (interactive)
   (pop-to-buffer (bqn-comint-buffer)))
 :hook (bqn-mode . bqn-comint-buffer))
```

Still getting `Buffer ’*BQN*’ exists but has no live process`

**Comment by AndersonTorres** [comment]
I am a bit busy with life things.

First, does this `"$HOME"` thing work? Dollars are shell syntax, not Elisp.
Usually we employ `(getenv HOME)` to obtain the `HOME` environment variable - and some `concat` to concatenate strings.

**Comment by b79** [comment]
Ah yes, that's it. I just set those interpreter variables using an explicit file path like
`/home/john/comp/lang/array-languages/bqn/CBQN/BQN` and evaluation is working now. Thanks for taking the time to point this out.
