### ISSUE TITLE
Move `bqn-{keymap,glyph}-mode` to the main file?

### ISSUE THREAD

**Issue by slotThe** [museoa/bqn-mode#81]
As it stands right now, both of those files essentially only define one interactive command, as well as a tiny major mode for viewing the respective information. Since neither of them are loaded by `bqn-mode.el` itself, this really rather useful functionality is actually pretty hard to discover (unlike in `gnu-apl-mode`, where similar functionality is readily available in the form of `C-c C-k` (`gnu-apl-show-keyboard`)). My proposal would be to either inline both files into `bqn-mode.el`, or at the very least `require` them when loading the major mode (so they appear under the `bqn-` prefix when pressing `M-x`)

**Comment by AndersonTorres** [comment]
Putting everything on a huge file has the small advantage of loading things faster. 
I will start with bqn-keymap at Develop branch first.

**Comment by AndersonTorres** [comment]
Now done

**Comment by slotThe** [comment]
Thanks!
